[project]
name = 'Inflation-resistance-treasury'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stx_Inflation-resistance-treasury]
path = 'contracts/stx_Inflation-resistance-treasury.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
